version: '3.7'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0
    ports:
      - 8000:8000
    
  redis:
    image: redis
    ports:
      - 6379:6379
    command: redis-server --port 6379
    volumes:
      - ./data:/data